on:
  workflow_dispatch:
  push:
    branches:
        - 'main'

permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Setup Node.js environment
      uses: actions/setup-node@v2.5.2
      with:
          node-version: '18.x'
          
    - name: Get dependencies
      run: npm install
      working-directory: backend/
      
    - name: Run node.js scraping script
      run: node index.js
      working-directory: backend/

    - name: Install react dependencies
      run: npm install
      working-directory: gh-pages/stuttgart-soccer-24

    - name: Build Frontend
      run: | 
        npm run build
      working-directory: gh-pages/stuttgart-soccer-24
    
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: gh-pages/stuttgart-soccer-24/dist
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'
